### PR TITLE
Indigo fixes

### PR DESCRIPTION
**Pull request by trainman419**
This pulls all of the recent changes on the hydro branch into the indigo branch, along with the calibration fixes from @kbogert and a few fixes of my own to silence the queue_size warnings that are new in Indigo.

I've tested this on my TB1 enough to verify that the sensors read properly, the robot drives around, and all of the diagnostics are green.

As a follow-up to this, I would like to see a release of the turtlebot_create stack for Indigo, so that Yujin doesn't drop support for it; see https://github.com/turtlebot/turtlebot/issues/170

### CODE REVIEW

**Comment by jihoonl** [comment]
Nice Thanks @trainman419

**Comment by trainman419** [comment]
Bump. Now that this is merged, can I get an indigo release so that we can proceed with https://github.com/turtlebot/turtlebot/issues/170 ?

**Comment by wjwwood** [comment]
@jihoonl I second @trainman419's bump, we're trying to get this stuff built on ARM, @jihoonl do you have any idea when you might have time to make a release?

**Comment by jihoonl** [comment]
Sure go ahead. As long as it builds we can release. 

@wjwoodward I am preparing to release yujin_ocs early next week. After that turtlebot should be ready to release.

**Pull request merged**
